import base64,gzip,hashlib,re,pathlib,subprocess
one=pathlib.Path("DEPLOY_labor_bundles.txt").read_text().strip()
b64=re.search(r"printf '%s' '([A-Za-z0-9+/=]+)'",one).group(1)
sh=gzip.decompress(base64.b64decode(b64)).decode()
print("sh matches file:",hashlib.sha256(sh.encode()).hexdigest()==hashlib.sha256(pathlib.Path('run_labor_bundles.sh').read_text(encoding='utf-8').encode()).hexdigest())
mm=re.search(r"printf '%s' '([A-Za-z0-9+/=]+)' \| base64 -d \| gunzip > \"\$TMP/app.py\"",sh)
print("embedded app==mirror:",gzip.decompress(base64.b64decode(mm.group(1))).decode()==pathlib.Path('/tmp/app_patched.py').read_text(encoding='utf-8'))
print("checks _LABOR_BUNDLES:", "_LABOR_BUNDLES" in sh)
r=subprocess.run(["bash","-n","run_labor_bundles.sh"],capture_output=True,text=True)
print("bash -n:","OK" if r.returncode==0 else r.stderr)
