#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""P2.6 — Development Set مستقل (22 حالة، مؤلَّف يدويًا من الصفر — صفر إعادة استعمال لأي جملة
من Holdout v2 أو Dev Set v2 أو Gold Set40 أو battery.json). **لا يُعرَض هذا الملف على Planner
أبدًا — حقيقة أرضية للتقييم فقط.** كل حالة: `complexity` (فئة التدرّج)، `question` (نص الوقائع
الخام كما سيُرسَل لـPlanner حرفيًا)، و`ground_truth_issues` (قائمة مسائل، كل مسألة تحمل
`issue_id` كنوني للتصنيف الداخلي فقط + `issue_type` + `dimensions`: كل بُعد
{dimension_id, dimension_text (وصف مرجعي للحكم الدلالي — لا يُعرَض على Planner)، status،
critical}). تصنيف `status`/`critical` هنا هو حكمي المستقل (لا نسخ من أي مصدر) مبني على القراءة
القانونية للوقائع كما وردت، لا اجتهادًا إضافيًا يتجاوز النص."""

DEV_SET = [
    # ================= NEGATIVE CONTROLS (لفظ قانوني بلا مسألة فعلية) =================
    {"id": "dv-neg-1", "complexity": "negative_control",
     "question": "القاضي الذي أصدر الحكم معروف بدقته الشديدة في تسبيب أحكامه، ونحن الآن نستأنف الحكم لخطأ في تطبيق القانون لا غير.",
     "ground_truth_issues": []},
    {"id": "dv-neg-2", "complexity": "negative_control",
     "question": "زوجي يعمل في شركة مقاولات كبيرة، وأريد أن أعرف إجراءات المطالبة بنفقة الأولاد بعد الطلاق المتفق عليه بيننا وديًا.",
     "ground_truth_issues": [{"issue_id": "CHILD_SUPPORT_CLAIM", "issue_type": "substantive",
                               "dimensions": [{"dimension_id": "CHILD_SUPPORT_ASSESSMENT",
                                                "dimension_text": "معايير تقدير نفقة الأولاد بعد الطلاق",
                                                "status": "required", "critical": True}]}]},
    {"id": "dv-neg-3", "complexity": "negative_control",
     "question": "استلمت شيكًا كهدية من والدي بمناسبة تخرجي، ولم أصرفه بعد لأنني أحتفظ به كتذكار، والآن أسأل عن كيفية تجديد جواز سفري المنتهي.",
     "ground_truth_issues": []},
    {"id": "dv-neg-4", "complexity": "negative_control",
     "question": "في نسبة كبيرة من عقود الإيجار التجاري، يشترط المالك زيادة سنوية للأجرة، وسؤالي هو هل يجوز للمالك بيع العين المؤجَّرة أثناء سريان عقد الإيجار؟",
     "ground_truth_issues": [{"issue_id": "SALE_DURING_LEASE", "issue_type": "substantive",
                               "dimensions": [{"dimension_id": "LEASE_SURVIVES_SALE",
                                                "dimension_text": "أثر بيع العين المؤجَّرة على استمرار عقد الإيجار القائم",
                                                "status": "required", "critical": True}]}]},

    # ================= SINGLE ISSUE =================
    {"id": "dv-sgl-1", "complexity": "single_issue",
     "question": "تبيَّن لي أن أحد أعضاء هيئة التحكيم التي تنظر نزاعي التجاري هو شريك سابق في شركة الطرف الآخر حتى قبل عام واحد، وأريد معرفة هل يحق لي طلب استبعاده.",
     "ground_truth_issues": [{"issue_id": "ARBITRATOR_DISQUALIFICATION", "issue_type": "procedural",
                               "dimensions": [
                                   {"dimension_id": "ARBITRATOR_INDEPENDENCE_GROUNDS",
                                    "dimension_text": "أسباب الطعن في استقلال وحياد المحكَّم (علاقة سابقة بأحد الأطراف)",
                                    "status": "required", "critical": True},
                                   {"dimension_id": "CHALLENGE_PROCEDURE_TIMING",
                                    "dimension_text": "إجراءات وميعاد تقديم طلب رد المحكَّم",
                                    "status": "required", "critical": False}]}]},
    {"id": "dv-sgl-2", "complexity": "single_issue",
     "question": "فُصلت من عملي فجأة دون إنذار مسبق بعد خمس سنوات خدمة متواصلة، وصاحب العمل يرفض دفع أي تعويض.",
     "ground_truth_issues": [{"issue_id": "UNLAWFUL_TERMINATION", "issue_type": "substantive",
                               "dimensions": [
                                   {"dimension_id": "NOTICE_PERIOD_REQUIREMENT",
                                    "dimension_text": "وجوب مهلة إنذار قبل إنهاء عقد العمل ومدتها",
                                    "status": "required", "critical": True},
                                   {"dimension_id": "END_OF_SERVICE_ENTITLEMENT",
                                    "dimension_text": "استحقاق مكافأة نهاية الخدمة وحسابها",
                                    "status": "required", "critical": True}]}]},
    {"id": "dv-sgl-3", "complexity": "single_issue",
     "question": "أبرمت عقد بيع سيارة مستعملة، وبعد التسليم اكتشفت عطلًا جوهريًا في المحرك كان البائع يعلم به ولم يخبرني.",
     "ground_truth_issues": [{"issue_id": "HIDDEN_DEFECT_CLAIM", "issue_type": "substantive",
                               "dimensions": [
                                   {"dimension_id": "SELLER_WARRANTY_HIDDEN_DEFECT",
                                    "dimension_text": "ضمان البائع للعيوب الخفية وأثر علمه المسبق بها",
                                    "status": "required", "critical": True},
                                   {"dimension_id": "DEFECT_CLAIM_DEADLINE",
                                    "dimension_text": "الميعاد الواجب لرفع دعوى العيب الخفي",
                                    "status": "conditional", "condition": "يتوقف على تاريخ اكتشاف العيب فعليًا",
                                    "critical": False}]}]},
    {"id": "dv-sgl-4", "complexity": "single_issue",
     "question": "شريكي في الشركة يرفض منذ ثلاثة أشهر دعوة الجمعية العمومية رغم طلبي المتكرر، وأخشى تعطُّل قرارات الشركة المصيرية.",
     "ground_truth_issues": [{"issue_id": "PARTNER_REFUSES_ASSEMBLY", "issue_type": "procedural",
                               "dimensions": [
                                   {"dimension_id": "COMPEL_ASSEMBLY_MECHANISM",
                                    "dimension_text": "الآلية القانونية لإلزام الشريك الممتنع بدعوة الجمعية أو دعوتها بديلًا",
                                    "status": "required", "critical": True}]}]},

    # ================= TWO ISSUES =================
    {"id": "dv-two-1", "complexity": "two_issue",
     "question": "زوجتي رفعت دعوى طلاق للضرر، وفي نفس الوقت تنكر أنني الأب الشرعي لابننا الثاني رغم أنه وُلد أثناء زواجنا الرسمي القائم.",
     "ground_truth_issues": [
         {"issue_id": "DIVORCE_FOR_HARM", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "HARM_DIVORCE_GROUNDS",
                           "dimension_text": "شروط وأدلة إثبات الضرر الموجب للتطليق",
                           "status": "required", "critical": True}]},
         {"issue_id": "PATERNITY_DENIAL_DURING_MARRIAGE", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "PATERNITY_PRESUMPTION_WITHIN_MARRIAGE",
                           "dimension_text": "قرينة ثبوت نسب المولود أثناء قيام الزواج وشروط نفيه (كاللعان)",
                           "status": "required", "critical": True}]}]},
    {"id": "dv-two-2", "complexity": "two_issue",
     "question": "وقَّعت المستأجرة شيكًا كضمان للإيجار، وبعد انتهاء العقد رفض المالك إخلاء تسليم الوحدة رغم سداد كل المستحقات وطالبها بصرف الشيك رغم ذلك.",
     "ground_truth_issues": [
         {"issue_id": "LANDLORD_WITHHOLDS_HANDOVER", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "TENANT_HANDOVER_RIGHT_AFTER_PAYMENT",
                           "dimension_text": "حق المستأجر في تسلُّم إخلاء الوحدة بعد سداد كل المستحقات",
                           "status": "required", "critical": True}]},
         {"issue_id": "GUARANTEE_CHEQUE_MISUSE", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "GUARANTEE_CHEQUE_AFTER_OBLIGATION_MET",
                           "dimension_text": "حكم صرف شيك الضمان بعد سقوط سبب الضمان (سداد كل الالتزام)",
                           "status": "required", "critical": True}]}]},
    {"id": "dv-two-3", "complexity": "two_issue",
     "question": "أُصيب عامل في موقع البناء أثناء العمل، وصاحب العمل يرفض تحمل تكاليف العلاج ويهدد بإنهاء عقده لأنه لم يعد قادرًا على العمل بنفس الكفاءة.",
     "ground_truth_issues": [
         {"issue_id": "WORK_INJURY_COMPENSATION", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "EMPLOYER_LIABILITY_WORK_INJURY",
                           "dimension_text": "مسؤولية صاحب العمل عن إصابة العمل وتكاليف العلاج",
                           "status": "required", "critical": True}]},
         {"issue_id": "TERMINATION_DUE_TO_INJURY", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "PROTECTION_FROM_TERMINATION_DURING_TREATMENT",
                           "dimension_text": "حماية العامل المصاب من الإنهاء أثناء فترة العلاج/العجز المؤقت",
                           "status": "required", "critical": True}]}]},
    {"id": "dv-two-4", "complexity": "two_issue",
     "question": "المدين الذي حرَّر لي كمبيالة توفي قبل حلول أجلها، وورثته يرفضون الاعتراف بالدين لأن التوقيع بخط والدهم المتوفى غير واضح في نظرهم.",
     "ground_truth_issues": [
         {"issue_id": "DEBT_AGAINST_ESTATE", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "CLAIM_AGAINST_DECEASED_ESTATE",
                           "dimension_text": "كيفية المطالبة بدين على تركة المتوفى ومدى مسؤولية الورثة",
                           "status": "required", "critical": True}]},
         {"issue_id": "SIGNATURE_AUTHENTICITY_DISPUTE", "issue_type": "evidentiary",
          "dimensions": [{"dimension_id": "HANDWRITING_EXPERT_PROCEDURE",
                           "dimension_text": "إجراءات إثبات صحة التوقيع المتنازع عليه (مضاهاة الخطوط)",
                           "status": "required", "critical": True}]}]},

    # ================= THREE-FOUR ISSUES =================
    {"id": "dv-multi-1", "complexity": "three_four_issue",
     "question": "تزوجت زواجًا عرفيًا لم يُوثَّق رسميًا، وزوجي الآن ينكر وقوع الزواج من الأساس، ولدينا طفل يرفض الاعتراف بنسبه له أيضًا، وأنا أطالبه بشيك كان قد حرَّره لي كنفقة ورفض صرفه البنك لعدم كفاية الرصيد.",
     "ground_truth_issues": [
         {"issue_id": "MARITAL_RELATIONSHIP_DENIAL", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "UNREGISTERED_MARRIAGE_PROOF",
                           "dimension_text": "إثبات قيام الزواج العرفي غير الموثَّق عند إنكاره",
                           "status": "required", "critical": True}]},
         {"issue_id": "LINEAGE_DENIAL", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "LINEAGE_ESTABLISHMENT_PROCEDURE",
                           "dimension_text": "إجراءات إثبات نسب الطفل عند إنكار الأب",
                           "status": "required", "critical": True}]},
         {"issue_id": "CHEQUE_CLAIM", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "BOUNCED_CHEQUE_CLAIM_BASIS",
                           "dimension_text": "أساس المطالبة بقيمة شيك مرتد لعدم كفاية الرصيد",
                           "status": "required", "critical": True}]},
         {"issue_id": "PRIOR_ADMIN_PROCEDURE", "issue_type": "procedural",
          "dimensions": [{"dimension_id": "MANDATORY_PRIOR_COMMITTEE_REVIEW",
                           "dimension_text": "وجوب عرض بعض هذه المسائل (كالنسب) على جهة إدارية مختصة قبل رفع الدعوى",
                           "status": "possible", "critical": False}]}]},
    {"id": "dv-multi-2", "complexity": "three_four_issue",
     "question": "شركتنا أبرمت عقد توريد مع مورِّد أجنبي، وتأخر التوريد شهرين عن الموعد المتفق عليه، فرفضنا استلام البضاعة وأوقفنا صرف الشيكات المؤجَّلة له، والمورِّد يهدد برفع دعوى ويطالب أيضًا بفوائد تأخير، بينما نحن نرى أن التأخير كان بسبب إغلاق ميناء الشحن قهريًا.",
     "ground_truth_issues": [
         {"issue_id": "SUPPLY_DELAY_BREACH", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "LATE_DELIVERY_BREACH_CONSEQUENCES",
                           "dimension_text": "أثر التأخر في التوريد على التزامات المشتري بالاستلام والدفع",
                           "status": "required", "critical": True}]},
         {"issue_id": "FORCE_MAJEURE_DEFENSE", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "FORCE_MAJEURE_APPLICABILITY",
                           "dimension_text": "مدى انطباق دفع القوة القاهرة (إغلاق الميناء) على التأخير",
                           "status": "conditional", "condition": "يتوقف على إثبات أن إغلاق الميناء كان قهريًا لا متوقَّعًا",
                           "critical": True}]},
         {"issue_id": "SUSPENDED_CHEQUES", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "WITHHOLDING_PAYMENT_INSTRUMENTS_LEGALITY",
                           "dimension_text": "مدى مشروعية إيقاف صرف الشيكات المؤجَّلة كرد فعل للإخلال المزعوم",
                           "status": "required", "critical": True}]},
         {"issue_id": "DELAY_INTEREST_CLAIM", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "DELAY_INTEREST_ENTITLEMENT",
                           "dimension_text": "أساس استحقاق فوائد التأخير المطالَب بها",
                           "status": "conditional", "condition": "يتوقف على ثبوت إخلال المشتري لا وجود عذر مشروع",
                           "critical": False}]}]},
    {"id": "dv-multi-3", "complexity": "three_four_issue",
     "question": "توفي والدي تاركًا ورثة من زوجتين (سنية وجعفرية المذهب) وأبناء من كلتيهما، وترك أيضًا شيكات لم تُصرف بعد باسم بعض الدائنين، وأحد إخوتي يطعن في صحة وصية والدي لأنها لم تُوثَّق رسميًا.",
     "ground_truth_issues": [
         {"issue_id": "MIXED_SECT_INHERITANCE", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "INHERITANCE_LAW_APPLICABLE_BY_SECT",
                           "dimension_text": "تحديد قانون المواريث الواجب التطبيق حسب مذهب المتوفى لا الورثة",
                           "status": "required", "critical": True}]},
         {"issue_id": "OUTSTANDING_CHEQUES_ESTATE", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "ESTATE_DEBTS_PRIORITY_OVER_DISTRIBUTION",
                           "dimension_text": "أولوية سداد ديون التركة (الشيكات المستحقة) قبل توزيعها على الورثة",
                           "status": "required", "critical": True}]},
         {"issue_id": "WILL_VALIDITY_CHALLENGE", "issue_type": "evidentiary",
          "dimensions": [{"dimension_id": "WILL_FORMALITY_REQUIREMENT",
                           "dimension_text": "شروط الشكل الرسمي اللازمة لصحة الوصية وأثر تخلُّفها",
                           "status": "required", "critical": True}]}]},

    # ================= CROSS-LAW =================
    {"id": "dv-cross-1", "complexity": "cross_law",
     "question": "طردت موظفة من عملها بعد أن أبلغت الإدارة بأنها حامل، وهي الآن تريد المطالبة بتعويض العمل والتعويض عن التمييز بسبب الحمل معًا.",
     "ground_truth_issues": [
         {"issue_id": "PREGNANCY_DISCRIMINATION_TERMINATION", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "PROTECTED_TERMINATION_DURING_PREGNANCY",
                           "dimension_text": "حماية العاملة الحامل من الفصل التعسفي بسبب الحمل (قانون العمل)",
                           "status": "required", "critical": True},
                          {"dimension_id": "MATERNITY_DISCRIMINATION_REMEDY",
                           "dimension_text": "أساس التعويض الإضافي عن التمييز بسبب الحمل إن وُجد نص خاص متمايز عن التعويض العمالي العام",
                           "status": "conditional", "condition": "يتوقف على وجود نص تمييز خاص متمايز لا مجرد فصل تعسفي عام",
                           "critical": False}]}]},
    {"id": "dv-cross-2", "complexity": "cross_law",
     "question": "استوردت شركتنا بضاعة عبر منصة إلكترونية أجنبية، ووصلت تالفة، والمنصة تطبِّق شروطًا إلكترونية موقَّعة رقميًا تحدُّ من مسؤوليتها، فهل هذه الشروط نافذة أصلًا وهل تُطبَّق عليها أحكام حماية المستهلك التقليدية؟",
     "ground_truth_issues": [
         {"issue_id": "ELECTRONIC_TERMS_VALIDITY", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "DIGITAL_SIGNATURE_CONTRACT_VALIDITY",
                           "dimension_text": "حجية الشروط الإلكترونية الموقَّعة رقميًا (قانون المعاملات الإلكترونية)",
                           "status": "required", "critical": True}]},
         {"issue_id": "CONSUMER_PROTECTION_OVERLAP", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "CONSUMER_PROTECTION_APPLICABILITY_TO_ECOMMERCE",
                           "dimension_text": "مدى سريان أحكام حماية المستهلك التقليدية على التجارة الإلكترونية رغم الشروط الخاصة",
                           "status": "required", "critical": True}]}]},
    {"id": "dv-cross-3", "complexity": "cross_law",
     "question": "أصدرت جهة إدارية قرارًا بإلغاء ترخيصي التجاري بحجة مخالفة بيئية، وأنا أرى أن القرار باطل شكلًا لعدم تسبيبه، وأريد أيضًا المطالبة بتعويض عن الأضرار التجارية التي لحقتني جراء هذا القرار.",
     "ground_truth_issues": [
         {"issue_id": "ADMIN_DECISION_ANNULMENT", "issue_type": "procedural",
          "dimensions": [{"dimension_id": "ADMIN_DECISION_REASONING_REQUIREMENT",
                           "dimension_text": "وجوب تسبيب القرار الإداري وأثر تخلُّفه على بطلانه شكلًا",
                           "status": "required", "critical": True},
                          {"dimension_id": "ANNULMENT_CLAIM_DEADLINE",
                           "dimension_text": "ميعاد رفع دعوى إلغاء القرار الإداري",
                           "status": "required", "critical": True}]},
         {"issue_id": "ADMIN_LIABILITY_DAMAGES", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "STATE_LIABILITY_FOR_UNLAWFUL_DECISION",
                           "dimension_text": "أساس مسؤولية الجهة الإدارية عن تعويض الأضرار الناتجة عن قرار غير مشروع",
                           "status": "conditional", "condition": "يتوقف على ثبوت بطلان القرار أولًا",
                           "critical": True}]}]},

    # ================= PROCEDURAL + SUBSTANTIVE =================
    {"id": "dv-procsub-1", "complexity": "procedural_substantive",
     "question": "رفعت دعوى مطالبة بدين تجاري منذ ثلاثة أشهر، ولم أُعلن خصمي بصحيفة الدعوى حتى الآن بسبب تغيير عنوانه، وأخشى سقوط الدعوى لعدم الإعلان قبل الفصل في أصل الحق.",
     "ground_truth_issues": [
         {"issue_id": "SERVICE_OF_PROCESS_FAILURE", "issue_type": "procedural",
          "dimensions": [{"dimension_id": "SERVICE_DEADLINE_AND_CONSEQUENCES",
                           "dimension_text": "ميعاد إعلان الخصم وأثر تعذُّره على سير الدعوى (كإعلان بديل أو شطب)",
                           "status": "required", "critical": True}]},
         {"issue_id": "COMMERCIAL_DEBT_CLAIM", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "COMMERCIAL_DEBT_BASIS",
                           "dimension_text": "أساس المطالبة بالدين التجاري ذاته",
                           "status": "required", "critical": True}]}]},
    {"id": "dv-procsub-2", "complexity": "procedural_substantive",
     "question": "خسرت دعوى في محكمة أول درجة بشأن ملكية عقار، وأريد استئناف الحكم، لكن المهلة النظامية للاستئناف قاربت على الانتهاء ومحاميّ السابق لم يُخطرني بالحكم إلا متأخرًا.",
     "ground_truth_issues": [
         {"issue_id": "APPEAL_DEADLINE_RISK", "issue_type": "procedural",
          "dimensions": [{"dimension_id": "APPEAL_DEADLINE_AND_EXTENSION_GROUNDS",
                           "dimension_text": "ميعاد الاستئناف وإمكانية مد الميعاد لعذر التأخر في الإخطار",
                           "status": "required", "critical": True}]},
         {"issue_id": "PROPERTY_OWNERSHIP_DISPUTE", "issue_type": "substantive",
          "dimensions": [{"dimension_id": "OWNERSHIP_PROOF_STANDARD",
                           "dimension_text": "معيار إثبات ملكية العقار المتنازع عليه",
                           "status": "required", "critical": True}]}]},

    # ================= TEMPORAL/VERSION =================
    {"id": "dv-temp-1", "complexity": "temporal_version",
     "question": "أبرمت عقد إيجار تجاري عام 2015 بشروط معينة، ثم صدر تعديل تشريعي عام 2020 غيَّر مدة الإخطار بإخلاء العين المؤجَّرة، والمالك الآن يريد إخلائي بالمدة الجديدة الأقصر رغم أن عقدي أُبرم قبل التعديل.",
     "ground_truth_issues": [{"issue_id": "AMENDMENT_TEMPORAL_APPLICABILITY", "issue_type": "temporal",
                               "dimensions": [{"dimension_id": "NON_RETROACTIVITY_VS_IMMEDIATE_EFFECT",
                                                "dimension_text": "هل يُطبَّق التعديل التشريعي الجديد بأثر فوري على عقود قائمة أُبرمت قبله أم يبقى النص القديم حاكمًا لها",
                                                "status": "required", "critical": True}]}]},
    {"id": "dv-temp-2", "complexity": "temporal_version",
     "question": "ارتكبت مخالفة إدارية في وقت كانت الغرامة المقررة لها ألف دينار، وقبل صدور القرار بتوقيع الجزاء صدر تعديل رفع الغرامة إلى ثلاثة آلاف دينار، فما الغرامة الواجب تطبيقها عليّ؟",
     "ground_truth_issues": [{"issue_id": "PENALTY_AMOUNT_TEMPORAL_CONFLICT", "issue_type": "temporal",
                               "dimensions": [{"dimension_id": "PENALTY_APPLICABLE_LAW_AT_VIOLATION_TIME",
                                                "dimension_text": "مبدأ تطبيق القانون الأصلح للمتهم/الأخف عقوبة عند تعاقب النصوص الجزائية-الإدارية",
                                                "status": "required", "critical": True}]}]},
    {"id": "dv-temp-3", "complexity": "temporal_version",
     "question": "زوجتي الجعفرية المذهب توفيت، وقانون الأحوال الشخصية الجعفري الذي كان ساريًا وقت زواجنا استُبدل بمرسوم جديد بعد وفاتها بأشهر ينظِّم الميراث بصيغة مختلفة، فأي نص يحكم توزيع تركتها؟",
     "ground_truth_issues": [{"issue_id": "INHERITANCE_LAW_TEMPORAL_CONFLICT", "issue_type": "temporal",
                               "dimensions": [{"dimension_id": "INHERITANCE_GOVERNED_BY_LAW_AT_DEATH",
                                                "dimension_text": "مبدأ خضوع تركة المتوفى للقانون الساري وقت الوفاة لا القانون اللاحق",
                                                "status": "required", "critical": True}]}]},

    # ================= EXCEPTION/DEFENSE =================
    {"id": "dv-exc-1", "complexity": "exception_defense",
     "question": "استلمت دفعة مالية من عميل بالخطأ مرتين لنفس الفاتورة، واستهلكتها في تسديد التزاماتي دون أن أنتبه للخطأ، والآن يطالبني برد المبلغ الزائد بعد سنتين من الواقعة.",
     "ground_truth_issues": [{"issue_id": "UNJUST_ENRICHMENT_RECOVERY", "issue_type": "substantive",
                               "dimensions": [
                                   {"dimension_id": "UNDUE_PAYMENT_RECOVERY_BASIS",
                                    "dimension_text": "أساس استرداد المبلغ المدفوع خطأً (دعوى الإثراء بلا سبب/غير المستحق)",
                                    "status": "required", "critical": True},
                                   {"dimension_id": "GOOD_FAITH_CONSUMPTION_DEFENSE",
                                    "dimension_text": "دفع حسن النية في استهلاك المبلغ كأثر على مدى الالتزام بالرد",
                                    "status": "possible", "critical": False},
                                   {"dimension_id": "RECOVERY_CLAIM_LIMITATION",
                                    "dimension_text": "مدى سريان مدة تقادم على دعوى استرداد غير المستحق بعد سنتين",
                                    "status": "conditional", "condition": "يتوقف على تحديد أمد التقادم النوعي لهذه الدعوى",
                                    "critical": True}]}]},
    {"id": "dv-exc-2", "complexity": "exception_defense",
     "question": "رفع عليّ خصمي دعوى تنفيذ سند بعد مضي سبع سنوات على تاريخ استحقاقه بلا أي مطالبة سابقة، وأنا أعتزم الدفع بسقوط حقه بالتقادم.",
     "ground_truth_issues": [{"issue_id": "LIMITATION_DEFENSE_ON_INSTRUMENT", "issue_type": "substantive",
                               "dimensions": [{"dimension_id": "INSTRUMENT_CLAIM_LIMITATION_PERIOD",
                                                "dimension_text": "مدة تقادم دعوى المطالبة بقيمة السند وبدء سريانها",
                                                "status": "required", "critical": True}]}]},
    {"id": "dv-exc-3", "complexity": "exception_defense",
     "question": "وقَّعت على إقرار بالدين تحت تهديد صاحبه بفضح أسرار عائلية، والآن يستعمل هذا الإقرار في دعوى ضدي وأنا أريد الدفع ببطلانه للإكراه.",
     "ground_truth_issues": [{"issue_id": "COERCED_ACKNOWLEDGMENT_VOIDANCE", "issue_type": "substantive",
                               "dimensions": [
                                   {"dimension_id": "DURESS_VITIATING_CONSENT",
                                    "dimension_text": "أثر الإكراه المعنوي (التهديد) على صحة الإقرار/الرضا في المحرر",
                                    "status": "required", "critical": True},
                                   {"dimension_id": "DURESS_PROOF_BURDEN",
                                    "dimension_text": "عبء إثبات واقعة الإكراه على من يدَّعيه",
                                    "status": "required", "critical": False}]}]},
]

if __name__ == "__main__":
    from collections import Counter
    print(f"DEV_SET size = {len(DEV_SET)}")
    print(Counter(c["complexity"] for c in DEV_SET))
    n_issues = sum(len(c["ground_truth_issues"]) for c in DEV_SET)
    n_dims = sum(len(i["dimensions"]) for c in DEV_SET for i in c["ground_truth_issues"])
    print(f"إجمالي المسائل: {n_issues}، إجمالي الأبعاد: {n_dims}")
